### ISSUE TITLE
"HotWater" not properly parsed - ERROR

### ISSUE THREAD

**Issue by BagiSenior** [eko/tado-exporter#80] opened 2021-01-17 09:01 UTC
Setup: TADO V3 with OpenTherm connection to gas boiler (combo - heating and water).

Exporter thorws an error while parsing "HotWater" component:

2021-01-17T08:57:38Z ERROR tado_exporter::tado::client] unable to retrieve home zone 'Hot Wat
er' state: error decoding response body: missing field `insideTemperature` at line 1 column 36

**Comment by BagiSenior** [comment] 2021-01-17 10:59
JSON response that most likely causes an issue:
request: "https://my.tado.com/api/v2/homes/[EDITED]/zones/0/state"
response:
{
	"tadoMode": "HOME",
	"geolocationOverride": true,
	"geolocationOverrideDisableTime": null,
	"preparation": null,
	"setting": {
		"type": "HOT_WATER",
		"power": "ON",
		"temperature": {
			"celsius": 55.0,
			"fahrenheit": 131.0
		}
	},
	"overlayType": null,
	"overlay": null,
	"openWindow": null,
	"nextScheduleChange": null,
	"nextTimeBlock": null,
	"link": {
		"state": "ONLINE"
	},
	"activityDataPoints": {},
	"sensorDataPoints": {}
}

**Comment by BagiSenior** [comment] 2021-01-17 12:13
And additional zone definition as received

{
		"id": 0,
		"name": "Hot Water",
		"type": "HOT_WATER",
		"dateCreated": "2021-01-15T18:56:30.499Z",
		"deviceTypes": [
			"BR02",
			"SU02"
		],
		"devices": [
			{
				"deviceType": "BR02",
				"serialNo": "**_[EDITED]_**",
				"shortSerialNo": "**_[EDITED]_**",
				"currentFwVersion": "74.3",
				"connectionState": {
					"value": true,
					"timestamp": "2021-01-17T10:41:32.480Z"
				},
				"characteristics": {
					"capabilities": []
				},
				"isDriverConfigured": true,
				"duties": [
					"ZONE_DRIVER"
				]
			},
			{
				"deviceType": "SU02",
				"serialNo": "**_[EDITED]_**",
				"shortSerialNo": "**_[EDITED]_**",
				"currentFwVersion": "73.1",
				"connectionState": {
					"value": true,
					"timestamp": "2021-01-17T10:34:32.894Z"
				},
				"characteristics": {
					"capabilities": [
						"INSIDE_TEMPERATURE_MEASUREMENT",
						"IDENTIFY"
					]
				},
				"batteryState": "NORMAL",
				"duties": [
					"ZONE_UI",
					"ZONE_LEADER"
				]
			}
		],
		"reportAvailable": false,
		"supportsDazzle": false,
		"dazzleEnabled": false,
		"dazzleMode": {
			"supported": false
		},
		"openWindowDetection": {
			"supported": false
		}
	}

**Comment by eko** [comment] 2021-01-24 14:16
Hi @BagiSenior, the error you mentioned in this issue is that the API returns a `insideTemperature` field but I cannot locate where this field is returned. I cannot find this field in the API responses your paste in your comments too.

Could you please provide an API request/response with this field so I could update the model?

Thank you

**Comment by cristicalin** [comment] 2021-10-03 07:45
Hi @eko! First off, great work on the exporter.

I'm hitting the same issue as @BagiSenior above.

It looks like the hot water controller (seems to always be reported as `zone/0/state`) has a different layout than the radiator controllers.

Example:

Hot-Water:
```json
{
  "tadoMode": "HOME",
  "geolocationOverride": false,
  "geolocationOverrideDisableTime": null,
  "preparation": null,
  "setting": {
    "type": "HOT_WATER",
    "power": "ON",
    "temperature": {
      "celsius": 55,
      "fahrenheit": 131
    }
  },
  "overlayType": null,
  "overlay": null,
  "openWindow": null,
  "nextScheduleChange": {
    "start": "2021-10-03T21:00:00Z",
    "setting": {
      "type": "HOT_WATER",
      "power": "OFF",
      "temperature": null
    }
  },
  "nextTimeBlock": {
    "start": "2021-10-03T21:00:00.000Z"
  },
  "link": {
    "state": "ONLINE"
  },
  "activityDataPoints": {},
  "sensorDataPoints": {}
}
```

Regular controller:

```json
{
  "tadoMode": "HOME",
  "geolocationOverride": false,
  "geolocationOverrideDisableTime": null,
  "preparation": null,
  "setting": {
    "type": "HEATING",
    "power": "OFF",
    "temperature": null
  },
  "overlayType": "MANUAL",
  "overlay": {
    "type": "MANUAL",
    "setting": {
      "type": "HEATING",
      "power": "OFF",
      "temperature": null
    },
    "termination": {
      "type": "MANUAL",
      "typeSkillBasedApp": "MANUAL",
      "projectedExpiry": null
    }
  },
  "openWindow": null,
  "nextScheduleChange": null,
  "nextTimeBlock": null,
  "link": {
    "state": "ONLINE"
  },
  "activityDataPoints": {
    "heatingPower": {
      "type": "PERCENTAGE",
      "percentage": 0,
      "timestamp": "2021-10-03T07:29:32.180Z"
    }
  },
  "sensorDataPoints": {
    "insideTemperature": {
      "celsius": 21.57,
      "fahrenheit": 70.83,
      "timestamp": "2021-10-03T07:35:24.181Z",
      "type": "TEMPERATURE",
      "precision": {
        "celsius": 0.1,
        "fahrenheit": 0.1
      }
    },
    "humidity": {
      "type": "PERCENTAGE",
      "percentage": 51.3,
      "timestamp": "2021-10-03T07:35:24.181Z"
    }
  }
}
```

It would seem that the code needs to treat the structure differently if `setting.type == "HEATING"` vs. `setting.type == "HOT_WATER"`.

**Comment by eko** [comment] 2021-10-03 10:14
Hi @cristicalin @BagiSenior,

Thank you for reporting this issue.

I think I just fixed this issue in the following pull request: https://github.com/eko/tado-exporter/pull/126

Could you be able to test the code in this particular branch?

I've added a new `type` label to metrics containing the device type (`HEATING`, `HOT_WATER`) and fixed the API response thanks to the JSON response you've provided to me.

Don't hesitate to let me know if you want me to merge and tag it as it does not break the actual ones.

Thank you

**Comment by cristicalin** [comment] 2021-10-03 15:15
Thanks for the quick fix @eko!
I just built a new container out of your fixed branch and I can confirm that it works.

**Comment by eko** [comment] 2021-10-03 17:47
Thank you for helping on this topic!

I've just created a new `v0.0.8` release containing this fix: https://github.com/eko/tado-exporter/releases/tag/v0.0.8

I will close this issue for now but feel free to reopen if you still have any issue :)

**Closed by eko** 2021-10-03 17:47 UTC
